### ISSUE TITLE
Question: I wonder is that a right way to set disk health false when meet syscall.EIO or  syscall.EROFS ?

### ISSUE THREAD

**Issue by templexxx** [westerndigitalcorporation/blb#8]
I read the codes about disk health in the manager. And have these questions:

1. I wonder is that a right way to set disk health false when meet syscall.EIO or  syscall.EROFS ? 

I'm curious to it because I don't know which error reported by device will be syscall.EIO or syscall.EROFS? Maybe the way in present will cause too many broken disks, we should implement a better way to deal with these kinds of errors?

Thanks!

**Comment by dnr** [comment]
That's a fair question. That behavior is certainly conservative, and we wanted to stay on the conservative side while we got more experience with blb in production. (As it turned out, blb didn't get that far into production use before shifting priorities at higher levels led us away from putting more resources into it.)

It seems to me that EIO and EROFS both obviously indicate problems, either at the hardware level or a corrupted filesystem, and in both cases it seems like a good idea to stop writing data to the disk, because we don't have as much confidence we can get it back again. EIO would likely be the hardware deciding it can't read a sector, and EROFS would be the filesystem deciding that there are enough errors that it's too risky to try writing any more.

An "unhealthy" disk can still serve reads, though. I think we don't automatically drain the disk at that point either, we wait for a higher level to mark it for draining (I could be remembering wrong, it's been a while). So overall the behavior seems like a reasonable balance to me, but of course it needs to be borne out by experience in production. Probably taking a closer look at the kernel paths to map hardware errors to syscall errnos would help too.

Out of curiosity, are you interested in using this code, or already using it somewhere?

**Comment by templexxx** [comment]
> That's a fair question. That behavior is certainly conservative, and we wanted to stay on the conservative side while we got more experience with blb in production. (As it turned out, blb didn't get that far into production use before shifting priorities at higher levels led us away from putting more resources into it.)
> 
> It seems to me that EIO and EROFS both obviously indicate problems, either at the hardware level or a corrupted filesystem, and in both cases it seems like a good idea to stop writing data to the disk, because we don't have as much confidence we can get it back again. EIO would likely be the hardware deciding it can't read a sector, and EROFS would be the filesystem deciding that there are enough errors that it's too risky to try writing any more.
> 
> An "unhealthy" disk can still serve reads, though. I think we don't automatically drain the disk at that point either, we wait for a higher level to mark it for draining (I could be remembering wrong, it's been a while). So overall the behavior seems like a reasonable balance to me, but of course it needs to be borne out by experience in production. Probably taking a closer look at the kernel paths to map hardware errors to syscall errnos would help too.
> 
> Out of curiosity, are you interested in using this code, or already using it somewhere?

@dnr 

Thank you for your detailed explanation!

The issue of detection of broken disk has bothered me for a long time. 

I used to be a developer in distributed storage area, and I found this repo. I think Western Digital must have much more experience than me, so I raised this issue asking for your helping :D

**Comment by dnr** [comment]
It's a hard problem, and I wouldn't take the code here as any example of best practices. It was just an initial attempt, to be tuned with experience.

This system was developed by a startup (Upthere) that was acquired by Western Digital. We did use some WD hardware, but we had no special insight into the disk failure detection problem, even after the acquisition.
